set dotenv-load

up-api:
  docker-compose build --no-cache api && docker-compose --env-file ./.env up api -d

down-api:
  docker-compose down -v api

up-fe:
  docker-compose build --no-cache frontend && docker-compose --env-file ./.env up frontend -d

down-fe:
  docker-compose down -v frontend

up-postgres:
  docker-compose build --no-cache postgres && docker-compose --env-file ./.env up postgres -d

down-postgres:
  docker-compose down postgres

up:
  docker-compose build --no-cache && docker-compose --env-file ./.env up -d

down:
  docker-compose down -v && docker volume rm $(docker volume ls -q | grep postgres)

prune:
  docker system prune --all --force --volumes

sqlc-gen:
  sqlc generate

migrate-create:
  cd packages/backend/db && migrate create -ext sql -dir migrations

migrate-up:
  cd packages/backend/db && migrate -database $POSTGRES_DB_URL_LOCAL -path migrations up

migrate-down:
  cd packages/backend/db && migrate -database $POSTGRES_DB_URL_LOCAL -path migrations down