set dotenv-load

up-api:
  docker-compose build --no-cache api && docker-compose --env-file ./.env up api -d

up:
  docker-compose build --no-cache && docker-compose --env-file ./.env up -d

down:
  docker-compose down

prune:
  docker system prune --all --force --volumes

fe-up:
  cd packages/frontend && next dev

be-up:
  cd packages/backend/api && fastapi dev main.py

sqlc-gen:
  sqlc generate

migrate-create:
  cd packages/backend/db && migrate create -ext sql -dir migrations

migrate-up:
  cd packages/backend/db && migrate -database $POSTGRES_DB_URL_LOCAL -path migrations up

migrate-down:
  cd packages/backend/db && migrate -database $POSTGRES_DB_URL_LOCAL -path migrations down