docker-up:
  docker-compose build --no-cache && docker-compose --env-file ./.env up -d

docker-down:
  docker-compose down

docker-prune:
  docker system prune --all --force --volumes

fe-up:
  cd packages/frontend && next dev

be-up:
  cd packages/backend/api && fastapi dev main.py

sqlc-gen:
  cd packages/backend && sqlc generate

migrate-create:
  cd packages/backend/db && migrate create -ext sql -dir migrations

migrate-up:
  cd packages/backend/db && migrate -database \"postgres://user:password@localhost:5432/mydatabase?sslmode=disable\" -path migrations up

migrate-down:
  cd packages/backend/db && migrate -database \"postgres://user:password@localhost:5432/mydatabase?sslmode=disable\" -path migrations down