# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import datetime
import pydantic
from typing import Optional


class Product(pydantic.BaseModel):
    id: int
    name: str
    price_cents: Optional[int]
    created_at: Optional[datetime.datetime]
    updated_at: Optional[datetime.datetime]
