# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import datetime
import pydantic
from typing import Optional


class Product(pydantic.BaseModel):
    id: int
    name: str
    pricecents: Optional[int]
    createdat: Optional[datetime.datetime]
    updatedat: Optional[datetime.datetime]
