# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
# source: products.sql
from typing import Optional
import uuid

import sqlalchemy

from db import models


CREATE_PRODUCT = """-- name: create_product \\:one
INSERT INTO products (name, price_cents)
VALUES (:p1, :p2)
RETURNING id, name, price_cents, created_at, updated_at
"""


GET_PRODUCT = """-- name: get_product \\:one
SELECT id, name, price_cents, created_at, updated_at
FROM products
WHERE id = :p1
"""


LIST_PRODUCTS = """-- name: list_products \\:many
SELECT id, name, price_cents, created_at, updated_at
FROM products
"""
